/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module vga_screen_counter_5 (
    input clk,
    input rst,
    output reg [9:0] x,
    output reg [9:0] y
  );
  
  
  
  wire [10-1:0] M_x_dim_value;
  counter_10 x_dim (
    .rst(rst),
    .clk(clk),
    .value(M_x_dim_value)
  );
  wire [10-1:0] M_y_dim_value;
  reg [1-1:0] M_y_dim_clk;
  counter_11 y_dim (
    .rst(rst),
    .clk(M_y_dim_clk),
    .value(M_y_dim_value)
  );
  
  always @* begin
    x = M_x_dim_value;
    y = M_y_dim_value;
    if (M_x_dim_value == 10'h280) begin
      M_y_dim_clk = 1'h1;
    end else begin
      M_y_dim_clk = 1'h0;
    end
  end
endmodule
