/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_plus_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    input usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [64-1:0] M_concept_e;
  reg [8-1:0] M_concept_a;
  reg [8-1:0] M_concept_b;
  concept_2 concept (
    .clk(clk),
    .a(M_concept_a),
    .b(M_concept_b),
    .e(M_concept_e)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    io_seg = 8'hff;
    io_sel = 4'hf;
    M_concept_a = io_dip[0+7-:8];
    M_concept_b = io_dip[8+7-:8];
    io_led = {M_concept_e[16+7-:8], M_concept_e[8+7-:8], M_concept_e[0+7-:8]};
  end
endmodule
