/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module concept_2 (
    input clk,
    input [7:0] a,
    input [7:0] b,
    output reg [63:0] e
  );
  
  
  
  reg [7:0] M_a_reg_d, M_a_reg_q = 1'h0;
  reg [7:0] M_b_reg_d, M_b_reg_q = 1'h0;
  reg [63:0] M_e_reg_d, M_e_reg_q = 1'h0;
  reg [31:0] M_temp_a_d, M_temp_a_q = 1'h0;
  reg [31:0] M_temp_b_d, M_temp_b_q = 1'h0;
  
  always @* begin
    M_temp_a_d = M_temp_a_q;
    M_temp_b_d = M_temp_b_q;
    M_a_reg_d = M_a_reg_q;
    M_b_reg_d = M_b_reg_q;
    M_e_reg_d = M_e_reg_q;
    
    M_a_reg_d = a;
    M_b_reg_d = b;
    e = M_e_reg_q;
    M_temp_a_d = (M_b_reg_q - M_a_reg_q) * (M_b_reg_q - M_a_reg_q);
    M_temp_b_d = (M_b_reg_q * M_temp_a_q) * (M_b_reg_q * M_temp_a_q);
    M_e_reg_d = M_temp_b_q * M_temp_b_q;
  end
  
  always @(posedge clk) begin
    M_a_reg_q <= M_a_reg_d;
    M_b_reg_q <= M_b_reg_d;
    M_e_reg_q <= M_e_reg_d;
    M_temp_a_q <= M_temp_a_d;
    M_temp_b_q <= M_temp_b_d;
  end
  
endmodule
