/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     SIZE = 10
     DIV = 2
     TOP = 800
     UP = 1
*/
module counter_3 (
    input clk,
    input rst,
    output reg [9:0] value
  );
  
  localparam SIZE = 4'ha;
  localparam DIV = 2'h2;
  localparam TOP = 10'h320;
  localparam UP = 1'h1;
  
  
  reg [11:0] M_ctr_d, M_ctr_q = 1'h0;
  
  localparam MAX_VALUE = 12'hc83;
  
  always @* begin
    M_ctr_d = M_ctr_q;
    
    value = M_ctr_q[2+9-:10];
    if (1'h1) begin
      M_ctr_d = M_ctr_q + 1'h1;
      if (1'h1 && M_ctr_q == 12'hc83) begin
        M_ctr_d = 1'h0;
      end
    end else begin
      M_ctr_d = M_ctr_q - 1'h1;
      if (1'h1 && M_ctr_q == 1'h0) begin
        M_ctr_d = 12'hc83;
      end
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ctr_q <= 1'h0;
    end else begin
      M_ctr_q <= M_ctr_d;
    end
  end
  
endmodule
