/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module instRom_3 (
    input [7:0] address,
    output reg [15:0] inst
  );
  
  
  
  always @* begin
    inst = 16'h0000;
    
    case (address)
      1'h0: begin
        inst = 16'h3200;
      end
      1'h1: begin
        inst = 16'h3180;
      end
      2'h2: begin
        inst = 16'h2210;
      end
      2'h3: begin
        inst = 16'h3101;
      end
      3'h4: begin
        inst = 16'h8221;
      end
      3'h5: begin
        inst = 16'h3f01;
      end
      3'h6: begin
        inst = 16'h3007;
      end
      3'h7: begin
        inst = 16'h3b00;
      end
      4'h8: begin
        inst = 16'h3c00;
      end
      4'h9: begin
        inst = 16'h3d00;
      end
      4'ha: begin
        inst = 16'h3101;
      end
      4'hb: begin
        inst = 16'h8bb1;
      end
      4'hc: begin
        inst = 16'h6b00;
      end
      4'hd: begin
        inst = 16'h300b;
      end
      4'he: begin
        inst = 16'h8cc1;
      end
      4'hf: begin
        inst = 16'h6c00;
      end
      5'h10: begin
        inst = 16'h300b;
      end
      5'h11: begin
        inst = 16'h8dd1;
      end
      5'h12: begin
        inst = 16'h6d00;
      end
      5'h13: begin
        inst = 16'h300b;
      end
      5'h14: begin
        inst = 16'h3100;
      end
      5'h15: begin
        inst = 16'h80f1;
      end
    endcase
  end
endmodule
