/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_plus_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [11:0] color,
    output reg h_sync,
    output reg v_sync
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [10-1:0] M_timer_x;
  wire [10-1:0] M_timer_y;
  wire [1-1:0] M_timer_h_sync;
  wire [1-1:0] M_timer_v_sync;
  wire [1-1:0] M_timer_on_screen;
  ind_sta_vga_timer_2 timer (
    .clk(clk),
    .rst(rst),
    .x(M_timer_x),
    .y(M_timer_y),
    .h_sync(M_timer_h_sync),
    .v_sync(M_timer_v_sync),
    .on_screen(M_timer_on_screen)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    color = 12'hfff;
    h_sync = M_timer_h_sync;
    v_sync = M_timer_v_sync;
    led[2+0-:1] = M_timer_h_sync;
    led[6+0-:1] = M_timer_v_sync;
    usb_tx = usb_rx;
  end
endmodule
