/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module instRom_5 (
    input [7:0] address,
    output reg [15:0] inst
  );
  
  
  
  always @* begin
    inst = 16'h0000;
    
    case (address)
      1'h0: begin
        inst = 16'h31fd;
      end
      1'h1: begin
        inst = 16'h2110;
      end
      2'h2: begin
        inst = 16'h6100;
      end
      2'h3: begin
        inst = 16'h3000;
      end
      3'h4: begin
        inst = 16'h32fa;
      end
      3'h5: begin
        inst = 16'h33fb;
      end
      3'h6: begin
        inst = 16'h34fc;
      end
      3'h7: begin
        inst = 16'h2120;
      end
      4'h8: begin
        inst = 16'h2130;
      end
      4'h9: begin
        inst = 16'h2140;
      end
    endcase
  end
endmodule
