/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module ind_sta_vga_timer_2 (
    input clk,
    input rst,
    output reg [9:0] x,
    output reg [9:0] y,
    output reg h_sync,
    output reg v_sync,
    output reg on_screen
  );
  
  
  
  wire [10-1:0] M_x_dim_value;
  counter_7 x_dim (
    .rst(rst),
    .clk(clk),
    .value(M_x_dim_value)
  );
  wire [10-1:0] M_y_dim_value;
  reg [1-1:0] M_y_dim_clk;
  counter_8 y_dim (
    .rst(rst),
    .clk(M_y_dim_clk),
    .value(M_y_dim_value)
  );
  
  always @* begin
    M_y_dim_clk = 1'h0;
    on_screen = 1'h0;
    x = 1'h0;
    y = 1'h0;
    h_sync = 1'h0;
    v_sync = 1'h0;
    if (M_x_dim_value <= 10'h280 && M_y_dim_value <= 9'h1e0) begin
      x = M_x_dim_value;
      y = M_y_dim_value;
      on_screen = 1'h1;
    end else begin
      x = 1'h0;
      y = 1'h0;
      on_screen = 1'h0;
    end
    if (10'h291 <= M_x_dim_value && M_x_dim_value <= 10'h2f0) begin
      h_sync = 1'h1;
    end else begin
      h_sync = 1'h0;
    end
    if (9'h1eb <= M_y_dim_value && M_y_dim_value <= 9'h1ec) begin
      v_sync = 1'h1;
    end else begin
      v_sync = 1'h0;
    end
    if (M_x_dim_value == 10'h320) begin
      M_y_dim_clk = 1'h1;
    end else begin
      M_y_dim_clk = 1'h0;
    end
  end
endmodule
